export const productList = [
  {
    id: 1,
    name: "Lọc dầu ô tô – Toyota Vios",
    image: "/images/product1.png",
    price: 299000,
    oldPrice: 329000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 2,
    name: "Lọc gió động cơ – Honda City",
    image: "/images/product2.jpg",
    price: 259000,
    oldPrice: 289000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 3,
    name: "Lọc nhiên liệu – Ford Ranger",
    image: "/images/product3.jpg",
    price: 319000,
    oldPrice: 349000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 4,
    name: "Lọc điều hòa – Hyundai Accent",
    image: "/images/gio3.png",
    price: 189000,
    oldPrice: 219000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 5,
    name: "Lọc dầu ô tô – Mazda 3",
    image: "/images/dau.png",
    price: 309000,
    oldPrice: 339000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 6,
    name: "Lọc gió động cơ – Kia Morning",
    image: "/images/giodongco.png",
    price: 249000,
    oldPrice: 279000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 7,
    name: "Lọc nhiên liệu – Mitsubishi Triton",
    image: "/images/locnhienlieu.jpg",
    price: 329000,
    oldPrice: 359000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 8,
    name: "Lọc điều hòa – Toyota Fortuner",
    image: "/images/locgio.png",
    price: 199000,
    oldPrice: 229000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 9,
    name: "Lọc dầu – Chevrolet Colorado",
    image: "/images/dau1.jpg",
    price: 299000,
    oldPrice: 329000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 10,
    name: "Lọc gió động cơ – Nissan Navara",
    image: "/images/gio4.png",
    price: 259000,
    oldPrice: 289000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 11,
    name: "Lọc nhiên liệu – Suzuki Ertiga",
    image: "/images/lieu1.jpg",
    price: 319000,
    oldPrice: 349000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 12,
    name: "Lọc điều hòa – VinFast Lux A2.0",
    image: "/images/hoa1.png",
    price: 199000,
    oldPrice: 229000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 13,
    name: "Lọc dầu – Mercedes C200",
    image: "/images/dau2.png",
    price: 359000,
    oldPrice: 389000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 14,
    name: "Lọc gió – Isuzu D-max",
    image: "/images/gio1.png",
    price: 279000,
    oldPrice: 309000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 15,
    name: "Lọc nhiên liệu – Toyota Innova",
    image: "/images/lieu2.jpg",
    price: 339000,
    oldPrice: 369000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 16,
    name: "Lọc điều hòa – Ford EcoSport",
    image: "/images/hoa2.jpg",
    price: 189000,
    oldPrice: 219000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 17,
    name: "Lọc dầu – BMW 320i",
    image: "/images/dau3.png",
    price: 379000,
    oldPrice: 409000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 18,
    name: "Lọc gió – Hyundai i10",
    image: "/images/gio2.png",
    price: 239000,
    oldPrice: 269000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
  {
    id: 19,
    name: "Lọc nhiên liệu – Mazda CX-5",
    image: "/images/lieu3.jpg",
    price: 359000,
    oldPrice: 389000,
    badge: "Giá cực sốc",
    isHotDeal: true,
  },
  {
    id: 20,
    name: "Lọc điều hòa – Kia Sorento",
    image: "/images/hoa3.png",
    price: 209000,
    oldPrice: 239000,
    badge: "Giá cực sốc",
    isHotDeal: false,
  },
];

